### PR TITLE
Work with current Sphinx release

### PR DESCRIPTION
**Pull request by peastman**
Changes to Sphinx caused this to break.  See https://github.com/pandegroup/openmm/issues/1685.  This PR makes it work again.

### CODE REVIEW

**Comment by swails** [comment]
You can get rid of the 3.3 line in the travis build matrix, since Sphinx doesn't work with Python 3.3 anymore.  That should fix the failure

**Comment by peastman** [comment]
Done, thanks.

**Comment by peastman** [comment]
All tests pass now.

**Comment by rmcgibbo** [comment]
Great!

**Comment by rmcgibbo** [comment]
@peastman: do you need me to cut a new release of `sphinxcontrib-autodoc_doxygen`?

**Comment by peastman** [comment]
Yes, that would be great.

**Comment by peastman** [comment]
Have you created a new PyPI release?  As of Friday builds were still failing because of this issue.

https://travis-ci.org/pandegroup/openmm/jobs/184720960

**Pull request merged**
